////////


#cmakedefine01 INCLUDE__SEGGERRTT

#if (INCLUDE__SEGGERRTT == 1)

#cmakedefine01 SEGGERRTT__DTTY_ENABLE

#define SEGGER_RTT_MAX_NUM_UP_BUFFERS	@SEGGERRTT__SEGGER_RTT_MAX_NUM_UP_BUFFERS@
#define SEGGER_RTT_MAX_NUM_DOWN_BUFFERS	@SEGGERRTT__SEGGER_RTT_MAX_NUM_DOWN_BUFFERS@
#define BUFFER_SIZE_UP		@SEGGERRTT__BUFFER_SIZE_UP@
#define BUFFER_SIZE_DOWN	@SEGGERRTT__BUFFER_SIZE_DOWN@

#endif /* (INCLUDE__SEGGERRTT == 1) */


